### ISSUE TITLE
Donwload puzzle data from AoC server

### ISSUE THREAD

**Issue by lancelote** [lancelote/advent_of_code#189]
Some caching should be also helpful. See Nina Zakharenko example https://github.com/nnja/advent_of_code_2018/blob/master/util.py#L59

**Comment by wimglenn** [comment]
Maybe https://github.com/wimglenn/advent-of-code-data will interest you.  Basic usage is like:

    from aocd import data

**Comment by lancelote** [comment]
Looks great, thank you, I will git it a try!
